// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxrs2MMsFVmvqp4aiCOfI8wze4okyB0MA',
    appId: '1:520534943213:android:cb9f31cc4c25d9eee933e4',
    messagingSenderId: '520534943213',
    projectId: 'night-eats-f0115',
    storageBucket: 'night-eats-f0115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEZrsKVKxqmG222hpdFLVS8SWSuTmS59c',
    appId: '1:520534943213:ios:13273300954bf23ee933e4',
    messagingSenderId: '520534943213',
    projectId: 'night-eats-f0115',
    storageBucket: 'night-eats-f0115.appspot.com',
    iosBundleId: 'com.kamisofts.nightEats',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJiBydeULU6ZFWBdYF7fTqFQJk6zIRVwY',
    appId: '1:520534943213:web:8033115cf520a4dde933e4',
    messagingSenderId: '520534943213',
    projectId: 'night-eats-f0115',
    authDomain: 'night-eats-f0115.firebaseapp.com',
    storageBucket: 'night-eats-f0115.appspot.com',
    measurementId: 'G-2N9Y8Q1HT6',
  );

}